services:
  n8n:
    Name: n8n
    Icon: /home/ossian/.makap/icons/n8n.png
    Compose: /home/ossian/.makap/compose/n8n.yaml
    URL: http://localhost:5678
    Type: Application
    Categories:
      - Development
      - Utility
    Exec: bash /home/ossian/repos/makap/sh/makap.sh up n8n
  google:
    Name: Google
    URL: http://www.google.com.br
    Type: Application
